### ISSUE TITLE
Write API documentation

### ISSUE THREAD

**Issue by null-a** [pyro-ppl/brmp#4]
Sub-tasks include:

* [x] Set-up tools (e.g. sphinx)
* [x] Add API docs
* ~~Write tutorials/examples~~ (Now #27)
* [x] Set-up doc hosting

**Comment by null-a** [comment]
Up until now, I've only added doc strings for what I consider to be the public interface, because I was aiming to generate compact and approachable documentation for end users. If we include every internal method, class, etc. in the docs, then the core interface (which is relatively small) will be lost in noise, which I suspect will significantly reduce their usefulness.

The approach of not adding doc strings to internal stuff isn't viable long term of course. What other approaches could we take to achieve something similar?

**Comment by neerajprad** [comment]
> If we include every internal method, class, etc. in the docs, then the core interface (which is relatively small) will be lost in noise, which I suspect will significantly reduce their usefulness.

> The approach of not adding doc strings to internal stuff isn't viable long term of course. What other approaches could we take to achieve something similar?

I agree. The way we have handled this in other repos is to also add docstring for clarity in internal functions / classes that have a stable API (for contributors) but not include them in our rst files so that these are excluded by sphinx. That ways these docstrings are available in IDEs / notebooks as well as for type inference, but don't end up in the online documentation and confuse the end users. To avoid duplicating documentation between private functions / methods and their public counterparts, you may also find it useful to write some doc copying utilities like the `copy_docs_from` decorator in Pyro.

**Comment by null-a** [comment]
@neerajprad: I notice that there's an RTD project already set-up for brmp -- thanks for making that happen. The doc [build is failing](https://readthedocs.org/projects/brmp/builds/), perhaps because we're installing big dependencies. Do you know if there's a fix we can apply from other projects? (I'd be happy to investigate if not.)

**Comment by neerajprad** [comment]
@null-a: I'm trying to fix that in #66. That issue is due to pip installing a large pytorch wheel by default, but it can be worked around by only installing the CPU wheels.
